// <auto-generated />
using System;
using Calendar.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calendar.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(CalendarDbContext))]
    partial class CalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calendar.Domain.Calendars.Aggregates.WorkoutDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("Id")
                        .HasName("pk_workout_days_id");

                    b.HasIndex("Date")
                        .IsUnique()
                        .HasDatabaseName("idx_workout_days_date");

                    b.ToTable("workout_days", (string)null);
                });

            modelBuilder.Entity("Calendar.Domain.Calendars.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_type");

                    b.Property<decimal>("ActualValue")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("numeric")
                        .HasColumnName("target_value");

                    b.Property<Guid?>("workout_day_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_exercises_id");

                    b.HasIndex("workout_day_id");

                    b.ToTable("exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_TargetValue_Positive", "target_value > 0");
                        });
                });

            modelBuilder.Entity("Calendar.Domain.Calendars.Exercise", b =>
                {
                    b.HasOne("Calendar.Domain.Calendars.Aggregates.WorkoutDay", null)
                        .WithMany("Exercises")
                        .HasForeignKey("workout_day_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Calendar.Domain.Calendars.Aggregates.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
